[package]
name = "craftlings-core"
description = "Core components for the Craftlings game."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
bevy.workspace = true
