name: build and test

on:
  # Run on `main` branch
  push:
    branches: ["main"]
  # Run on branches with an open PR targeting `main`
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo build --verbose --all-targets --all-features --locked

  clippy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all --all-targets --all-features --workspace -- --deny warnings

  fmt:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --version
      - run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: build
    steps:
      - name: install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: rust-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo test --verbose --all-features --workspace
